package ui

var activityPhrasesChineseNortheastNatural = activityPhrases(activityNortheast, `
搁这儿寻思呢…
我再好好合计合计…
先把零碎儿归拢归拢…
这旮旯我再瞅瞅…
我搁这儿盘算呢…
这几个念头我再扒拉扒拉…
这事儿可得细琢磨…
我再倒腾一遍…
这玩意儿还挺绕…`)

var activityPhrasesChineseNortheastPlayful = activityPhrases(activityNortheast, `
这脑回路我再捅咕两下…
先把几个念头归拢到一块儿…
脑瓜子搁后台忙活呢…
这条思路跑偏了，往回整整…
逻辑犄角旮旯再扫扫…
这几个如果我再扒拉扒拉…
脑瓜子换个路数再来…
这茬儿先搁脑子里过遍筛子…
先把跑偏的念头拽回来…
让几个前提先唠明白…
这脑洞我再归拢归拢…
先把反例叫过来唠两句…
脑瓜里头正挨个叫号呢…
这几个弯儿得挨个整明白…
先把思路边边角角扫一遍…
脑回路有点拧巴，我给捋顺…
先把逻辑零碎儿攒到一块…
这条思路再倒腾倒腾…
脑瓜子正给假设对账呢…
先把卡壳的地方整明白…
这几个条件我再掂量掂量…`)

var activityPhrasesChineseNortheast = joinActivityPhrases(
	activityPhrasesChineseNortheastNatural,
	activityPhrasesChineseNortheastPlayful,
)

var activityPhrasesChineseSichuanNatural = activityPhrases(activitySichuan, `
莫慌，等我理一哈…
脑壳先转两圈嘛…
这哈儿还没整醒豁…
要得，接到整…
等我再想哈儿嘛…
等我把它理伸抖…
莫忙，我再琢磨哈儿…
这点点要再看哈儿…
莫急，等我想醒豁…`)

var activityPhrasesChineseSichuanPlayful = activityPhrases(activitySichuan, `
莫慌，等我把逻辑理伸抖…
脑壳里头还在排队，等一哈…
这条思路有点打脑壳，再琢磨哈儿…
让几个假设先摆哈龙门阵…
等我把几个条件理伸抖…
这条逻辑有点扯拐，等我整哈…
莫忙，脑壳里头还在过招…
等我把跑偏的念头逮回来…
这哈儿先给反例让个位…
几个前提摆到一堆再看…
这条分支绕得很，慢慢整…
莫慌，我给思路换个走法…
脑壳先给逻辑腾个位…
等我把边边角角弄醒豁…
这几个如果还要摆一哈…
莫忙，等逻辑自己走两步…
脑壳里头还在打转转…
脑壳有点吵，先关哈麦…
这条思路再整巴适点…
莫急，先把前后摆清楚…
脑回路绷紧了，先松一哈…`)

var activityPhrasesChineseSichuan = joinActivityPhrases(
	activityPhrasesChineseSichuanNatural,
	activityPhrasesChineseSichuanPlayful,
)

var activityPhrasesChineseCantoneseNatural = activityPhrases(activityCantonese, `
等我谂下先…
度紧桥，等阵先…
等我谂多阵先…
俾我再谂清楚啲…
等阵，我度下先…
谂紧第二条路…
等我睇多两眼…
呢个谂法要再度下…
倒转嚟再睇一次先…`)

var activityPhrasesChineseCantonesePlayful = activityPhrases(activityCantonese, `
等我帮逻辑度多条桥先…
条思路仲喺度兜，等我捉返佢先…
等我同几个假设倾两句先…
个脑仲喺后台忙紧…
呢条逻辑要再执顺啲…
等我帮前提排返好队先…
几个如果仲喺度打交…
等我捉返条主线先…
等我睇下直觉有冇走焦先…
呢条分支摆住先，睇埋另一边…
等我将几个可能摊开睇…
个脑仲喺度重新编译…
等我帮反例留个位先…
呢条思路要再兜多个圈…
等我同边界条件对下口供…
几个前提仲未倾掂…
等我帮逻辑执返齐整…
呢个假设要再试多次…
个脑仲喺度捞紧料…
等我兜去另一边睇下先…
条逻辑有啲打结，等我拆返开先…`)

var activityPhrasesChineseCantonese = joinActivityPhrases(
	activityPhrasesChineseCantoneseNatural,
	activityPhrasesChineseCantonesePlayful,
)
